### ISSUE TITLE
Traitement des fichiers wma 

### ISSUE THREAD

**Issue by sora41** [sora41/music-sort#10]
premier piste évoquer la conversion en MP3 (vérifie si il y a une perte en qualité)
 voir les liens suivant :

https://www.qwant.com/?q=lib%20java%20convert%20wma%20to%20mp3&t=web

https://www.youtube.com/watch?v=_wIvXsuF-DE

https://stackoverflow.com/questions/4997923/is-there-any-pure-java-way-to-convert-wav-to-mp3

**Comment by sora41** [comment]
recherche comment traité les fichier wma

**Comment by floGalloni** [comment]
convertir wma ver flac (foobar2000 logiciel) ,wondersharestreamingaudio recorder logiciel capture de output audio

recherche lib java qui converti wma vers flac

http://www.jthink.net/jaudiotagger/index.jsp

nouvelle lib trouver pour prendre en charge le fichier WMA

**Comment by floGalloni** [comment]
on va teste la lib sur le mp3 pour la mettre en oeuvre

**Comment by floGalloni** [comment]
problemme de log rencomptrer voir se liens piste de resolution https://stackoverflow.com/questions/50778442/how-to-disable-jaudiotagger-logger-completely

**Comment by sora41** [comment]
generation des log par la lib jaudiotagger reussi , extractiond es inofrmation des WMA reussi , realisation du repository WMA resussi , 
reste a faire : 
integre ajoute les wma dans le filtre des fichier pris en charge .
reprendre l architecture pour apelle bon repository en fonction de la nature du fichier

**Comment by floGalloni** [comment]
filtre de fichier ajouter avec en plus un enumere

**Comment by floGalloni** [comment]
ajout de l enumere et de la creation d'un instance des repository en fonction  de celuici en utilisant la reflexivité de java
