### ISSUE TITLE
Traitement des fichiers wma

### ISSUE THREAD

**Issue by sora41** [sora41/music-sort#13]
voir les liens suivant :

https://www.qwant.com/?q=lib%20java%20convert%20wma%20to%20mp3&t=web

https://www.youtube.com/watch?v=_wIvXsuF-DE

https://stackoverflow.com/questions/4997923/is-there-any-pure-java-way-to-convert-wav-to-mp3

**Comment by floGalloni** [comment]
convertir wma ver flac (foobar2000 logiciel) ,wondersharestreamingaudio recorder logiciel capture de output audio

**Comment by floGalloni** [comment]
recherche lib  java qui converti wma vers flac

**Comment by floGalloni** [comment]
http://www.jthink.net/jaudiotagger/index.jsp

nouvelle lib trouver pour prendre en charge le fichier WMA
