### ISSUE TITLE
test la posiblite de faire une interface graphique

### ISSUE THREAD

**Issue by floGalloni** [sora41/music-sort#15]
recherche les librairie utilisable

**Comment by floGalloni** [comment]
étudie l'utilisation de javaFX

**Comment by floGalloni** [comment]
pour utiliser les librairi javafx il faut utiliser la compilance 1.8

**Comment by sora41** [comment]
reprendre par les base https://openclassrooms.com/fr/courses/26832-apprenez-a-programmer-en-java/23108-creez-votre-premiere-fenetre

**Comment by sora41** [comment]
apres reflexion dans un premier temps nous allons utiliser swing
