### ISSUE TITLE
ajouter la gestion des logs

### ISSUE THREAD

**Issue by floGalloni** [sora41/music-sort#4]
voir
	 cree un class file a qui on ajoute les log
	 http://imss-www.upmf-grenoble.fr/prevert/Prog/Java/CoursJava/fichierDeLogs.html
 VOIR TESTLOG projet

	//http://docs.oracle.com/javase/6/docs/api/java/util/logging/FileHandler.html
https://www.jmdoudoux.fr/java/dej/chap-logging.htm
		//https://pierrejean.wp.imt.fr/2014/02/18/java-log-dans-eclipse/
		//https://www.programmez.com/tutoriels/logging-dans-java
https://www.mkyong.com/logging/log4j-hello-world-example/
https://stackoverflow.com/questions/31840/java-logging-vs-log4j

**Comment by floGalloni** [comment]
branche cree  integration dans le projet en cours

**Comment by sora41** [comment]
https://www.jmdoudoux.fr/java/dej/chap-logging.htm
faire un test de mise en oeuvre avec log4J 
 
simple utilisation car donne un wrapper 
log4j est tres rependu et a l'air plus riche je pense l utiliser sur l application , quid de la mise en oeuvre

**Comment by sora41** [comment]
https://cyberzoide.developpez.com/tutoriels/java/logging/#LI

pour amelloration des log voir ce liens

**Comment by sora41** [comment]
grace a l'apport de maven j'ai enfin pu installer log4j test en cours , utiilisation de log4j sera liee a la reussite de l'utilisation de maven sur le projet existant

**Comment by sora41** [comment]
remplacer le système de log natif par les logs de log4j  (voir dans le dépendance de Maven )

**Comment by floGalloni** [comment]
ajout de log4j faite  avec sorti des log dans un fichier et un fichier de configuration
